### ISSUE TITLE
能否提供正确的postgres数据库初始化文件？

### ISSUE THREAD

**Issue by dr1nkw4ter** [funnyzpc/mee-admin#4]
现在的两个.sql，一个导入报错，一个导入成功后缺少表.

**Comment by funnyzpc** [comment]
最近比较忙，下周结束前我抽时间维护一版~，感谢~

**Comment by dr1nkw4ter** [comment]
好的 感谢～

**Comment by funnyzpc** [comment]
@dr1nkw4ter  您好，我已经发版了，请再试试看，之前初始化用的是备份脚本，我改了下，用最新的就好了；若您运行应用仍存在问题可直接联系我 : funnyzpc@gmail.com （QQ或WX）
![image](https://user-images.githubusercontent.com/25891320/140297695-1d17831d-1bfa-4f6e-9f79-bb711cca9c88.png)
