### ISSUE TITLE
能否说一下各个版本比如postgresql

### ISSUE THREAD

**Issue by CyberIKUN** [funnyzpc/mee-admin#5]

**Comment by funnyzpc** [comment]
### 真不好意思，回复较晚 ； 目前主要因为中间上传文件少了一些东西，所以后续补充了下，document下的sql文件仅保留最新的，使用最新的即可，另外如果您需要连接MySQL，请删除mapper中的::date强转义；如果您使用postgres（比较推荐) ,也可以删除mapper中的强转义，同时需要在jdbc后方添加参数： jdbc:postgresql://127.0.0.1:5432/mee?stringtype=unspecified&currentSchema=public

**Comment by funnyzpc** [comment]
@lixuyong2014 
 真不好意思，回复较晚 😂； 目前是因为中间上传文件少了一些东西，所以后续补充了下，document下的sql文件仅保留最新的，使用最新的即可，另外如果您需要连接MySQL，请删除mapper中的::date强转义；如果您使用postgres（比较推荐) ,也可以删除mapper中的强转义，同时需要在jdbc后方添加参数： jdbc:postgresql://127.0.0.1:5432/mee?stringtype=unspecified&currentSchema=public
