### ISSUE TITLE
应用系统存在任意文件读取漏洞

### ISSUE THREAD

**Issue by zaizainani** [funnyzpc/mee-admin#8]
尊敬的作者你好，我在代码审计过程中发现了当前应用系统存在任意文件读取漏洞，详情可以参考我上传的文件，谢谢
[anyfiledown-en.pdf](https://github.com/funnyzpc/mee-admin/files/12544186/anyfiledown-en.pdf)

**Comment by funnyzpc** [comment]
文件功能是从别处移植过来的，暂时加了些校验，需要的同志们尽量使用专业的文件系统
